services:
  app:
    image: golang:latest
    container_name: app
    volumes:
      - ./app:/app
    working_dir: /app
    command: go run main.go
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=recipes
    networks:
      - app-network
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - app-network
volumes:
  mysql_data:
networks:
  app-network:
    driver: bridge